# Generated by Django 5.0.6 on 2024-12-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_film_image_url_film_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
